import { MATCH_BALL_OPTIONS } from './constants.js';

export const state = {
  rootEl: null,
  titleScreenEl: null,
  playerSetupEl: null,
  playerSetupContainerEl: null,
  flyoverOverlayEl: null,
  controlsModalEl: null,
  mainMenuSettingsModalEl: null,
  titleBrandBall: null,

  callbacks: {
    onStartMatch: null,
    onStartPractice: null,
    onPlayerConfigChange: null,
    onOpenSettings: null,
    onSkipFlyover: null,
    onEnterSetup: null,
    onExitSetup: null,
    onRenderSettingsChange: null,
  },

  playerConfigs: [
    {
      name: 'Player 1',
      type: 'human',
      difficulty: 'medium',
      aggressiveness: 0.60,
      team: 'home',
      variant: 'classic',
      primaryColor: 0xd90429,
      cameraMode: 'chase',
    },
    {
      name: 'Player 2',
      type: 'human',
      difficulty: 'medium',
      aggressiveness: 0.60,
      team: 'away',
      variant: 'classic',
      primaryColor: 0x1d4ed8,
      cameraMode: 'chase',
    },
  ],

  currentSetupMode: 'match',
  setupPage: 1,
  currentBallOptions: MATCH_BALL_OPTIONS,
  selectedMatchBall: 'random',
  selectedMatchDuration: 300,
  selectedMatchArena: (typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('arena')) === 'bowl' ? 'bowl' : 'court',
  matchBallCards: [],
  matchDurationButtons: [],
  arenaButtons: [],
  matchRulesBoxEl: null,
  matchRulesFocusRow: 0, // 0: ball, 1: duration, 2: arena, 3: ready, 4: start

  lobbyTitleEl: null,
  lobbySubtitleEl: null,
  lobbyBadgeEl: null,
  columnsBoxEl: null,
  col1El: null,
  col2El: null,
  col1HeaderLabelEl: null,
  matchBallCardsRowEl: null,
  matchBallHeaderTitleEl: null,
  matchBallHeaderDescEl: null,

  playerTypeButtons: [[], []],
  playerTeamButtons: [[], []],
  playerSwatchButtons: [[], []],
  playerPhysiqueButtons: [[], []],
  playerCameraSelects: [null, null],
  playerReadyButtons: [null, null],
  playerInputBadges: [null, null],
  playerRowElements: [[], []],
  playerFocusRow: [0, 0],
  focusedColumn: 0, // 0 for Player 1, 1 for Player 2
  btnStartMatch: null,
  btnNext: null,
  btnBack: null,
  btnReadyP1: null,
  btnReadyP2: null,
  playerReadyState: [false, false],
  matchCountdownInterval: null,
  matchCountdownSecs: 0,
  matchCountdownActive: false,
  readyBannerEls: [null, null],
  ctrlTagEls: [null, null],
  titleButtons: [],
  titleFocusIndex: 0,
  gamepadPollHandle: null,
  titlePrevPads: [{ up: false, down: false, a: false, b: false, start: false, back: false }],
  prevPads: [
    { up: false, down: false, left: false, right: false, a: false, b: false, x: false, y: false, start: false, lb: false, rb: false },
    { up: false, down: false, left: false, right: false, a: false, b: false, x: false, y: false, start: false, lb: false, rb: false },
  ],
};
